name: 'Update Issue Action'
description: 'Updates issue titles and labels based on issue content and provided options.'
inputs:
  github-token:
    description: 'GitHub token for authorizing API calls'
    required: true
  issue-number:
    description: 'The number of the issue to update'
    required: true
  config:
    description: 'JSON string of configuration options for custom behavior'
    required: false
    default: '{}'
runs:
  using: 'node20'
  main: 'index.js'
