import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { Suspense } from "react";
// import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const headerList = headers();
  // const context = headerList.get("context");

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Suspense fallback={null}>{children}</Suspense> */}
        {children}
      </body>
    </html>
  );
}
