name: Manage Pull Requests and Issues
run-name: ${{github.actor}} PR opend or edited for ${{github.repository}}. Executing action `manage-pullrequest-issue` for ${{github.actor}} with custom confiration.

on:
  pull_request:
    types: [opened, edited]
    branches:
      - "*"
  issues:
    types: [opened, edited]

jobs:
  manage-general-prs-issues:
    name: Manage General PRs and Issues
    runs-on: ubuntu-latest

    if: github.actor != 'dependabot[bot]'
    steps:
      - name: 1. Checkout Repository - ${{github.repository}}
        id: checkout-repository
        uses: actions/checkout@v3

      - name: 2. Set up Node.js 18 for Action to Run
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Updated to Node.js 18

      - name: 3. Install Dependencies for Manage-PullRequest-Issue Action
        id: install-dependencies
        run: |
          cd .github/actions/manage-pullrequest-issue
          npm install
        continue-on-error: false

      - name: 4. Build Action and Transpile TypeScript to JavaScript
        id: build-action
        run: |
          cd .github/actions/manage-pullrequest-issue
          npm run build
        continue-on-error: false

      - name: 5. Run Action passing in Args from YML Configuration
        id: run-action
        uses: ./.github/actions/manage-pullrequest-issue
        with:
          actor: "all" # Use a wildcard or manage actor differently in the custom action
          branches: "main,develop"
          event_types: "pull_request,issues" # Event Types to be manage
          title_prefix: "" # No default prefix for this action. Should be set dynamically.
          labels: "manage-pr-issue,test"
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use PAT for testing purposes
